server:
  servlet:
    context-path: /zhu
  port: 1234
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ip/region?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: 
    password: 
  freemarker:
    cache: false
    checkTemplateLocation: true
    charset: utf-8
    suffix: .ftl
    request-context-attribute: request
    template-loader-path:classpath: /templates/
    contentType: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    enabled: true
    settings:
      classic_compatible: true

mybatis:
  typeAliasesPackage: com.springboot.example.model
  mapperLocations: classpath:/mapper/*.xml

#debug=true
#freemarker的配置文件



age: 3000


