server:
  servlet:
    context-path: /zhu
  port: 1234
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.16.16.143:3306/region?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: dev_rp
    password: ziroomdb
  freemarker:
    cache: false
    checkTemplateLocation: true
    charset: utf-8
    suffix: .ftl
    request-context-attribute: request
    template-loader-path:classpath: /templates/
    contentType: text/html


mybatis:
  typeAliasesPackage: com.springboot.example.model
  mapperLocations: classpath:/mapper/*.xml

#debug=true
#freemarker的配置文件



age: 3000


